export enum DirectoryActionType {
  FETCH_STRUCTURE = 'FETCH_STRUCTURE',
  ADD_SELECTED = 'ADD_SELECTED',
  REMOVE_SELECTED = 'REMOVE_SELECTED',
  ADD_ITEM = 'ADD_ITEM',
  EDIT_ITEM = 'EDIT_ITEM',
  DELETE_ITEM = 'DELETE_ITEM',
}
