export enum DirectoryActionType {
  FETCH_STRUCTURE = 'FETCH_STRUCTURE',
  FETCH_STRUCTURE_SUCCESS = 'FETCH_STRUCTURE_SUCCESS',
  ADD_SELECTED = 'ADD_SELECTED',
  REMOVE_SELECTED = 'REMOVE_SELECTED',
  ADD_ITEM = 'ADD_ITEM',
  EDIT_ITEM = 'EDIT_ITEM',
  DELETE_ITEM = 'DELETE_ITEM',
  CHANGE_CONTENT = 'CHANGE_CONTENT',
  SET_ACTIVE_TAB = 'SET_ACTIVE_TAB',
  REMOVE_FROM_TABS = 'REMOVE_FROM_TABS',
}
